### PR TITLE
Collaboration levels dev

### PR DESCRIPTION
**Pull request by 69mb**
Read only collaboration level added for #48

### CODE REVIEW

**Comment by ekala** [comment]
Some notes:
- Visual distinction between editors and viewers
- Tooltips to enable users distinguish between editors and views

A question: Will changes to the collaboration level of a given collaborator be made through the "Add Collaborator" dialog or can that be effected from the collaborators listing?

**Comment by 69mb** [comment]
There is already a distinction between viewers and editors in the
listing. The level is shown with the name.

Will add tooltips.

No change to collaboration level currently. The collaborator has to be
readded to change it.

## 

Brian

On 24 Jul 2012, at 05:00 PM, Emmanuel Kala
reply@reply.github.com
wrote:

**Comment by ekala** [comment]
Re-adding the collaborator will generate another notification message because the action shall be logged in `user_actions`. Perhaps check if an invite notification (for the bucket/river) had already been sent to the user?

**Comment by 69mb** [comment]
Editing of collaboration levels and tool tips added in a1a3fa9.

**Comment by ekala** [comment]
+1 for merge. @Deathshiver @dkobia ?

**Comment by nlewis2142** [comment]
:+1:

**Comment by 69mb** [comment]
Guys, can we merge our own branches only when we are ready to deploy.

**Pull request merged**
