### PR TITLE
Change license to AGPL

### PR DESCRIPTION
**Pull request by ekala**
- Changed the SwiftRiver license from GPLv3 to AGPL. The changes have
  been applied to the core applicatication.
- TODO: Propagate license changes to Ushahidi-authored plugins

### CODE REVIEW

**Comment by 69mb** [comment]
+1

**Comment by dkobia** [comment]
Yep +1

**Comment by heatherleson** [comment]
Will the license change be communicated during the community call today?  Also, what does this mean for plug-in authors?  Should we not be communicating with them in advance?
"Changed the SwiftRiver license from GPLv3 to AGPL. The changes have been applied to the core applicatication.

```
TODO: Propagate license changes to Ushahidi-authored plugins"
```

**Comment by dkobia** [comment]
The AGPL has less to do with plugins and more to do with protecting the core actually. Because plugins are just hooking in and have their own code, our legal counsel advices that they are not derivative and hence not beholden to the gpl, making a case for proprietary extensions.

**Pull request merged**
