### PR TITLE
Quotas for channel options - Closes #216

### LINKED ISSUE #216: Quotas for channel options
A way to limit the no. of channel parameters that a user can specify e.g. 100 RSS URLs. 10 Twitter keywords, 15 Twitter users etc.

The quotas would be per user so it wouldn't matter how many rivers they create. We would therefore need to keep tabs on each user's usage and adjust the same when they delete an option or river.

**NOTE** Also handle cases where the options are separated by ","

### PR DESCRIPTION
**Pull request by ekala**
- The channel quotas are only configurable by the administrator so the
  function is accessed via the "Site Settings" menu item.
  Channel Quotas
- This feature tracks how many channel options each user has used up.
  We therefore keep track of each user's usage each time a channel option
  is added/removed. When a user maxes out the limit, the API returns a
  status 400
- The quotas are only for channel options that are specified via a
  textbox and the premise is that users specify one option per textfield.
- On the UI, each quota item is saved individually:
  Save Quota Item

### CODE REVIEW

**Comment by dkobia** [comment]
Not absolutely necessary, but it might be good to add the model relationships as well? re **user** has_many **user_quotas** and the reverse belongs_to etc etc.

**Comment by dkobia** [comment]
Noticed this about the Email Channel -- it has no setting. Maybe its the grouped options causing this issue?

**Comment by ekala** [comment]
The email channel plugin adds a column to the rivers table. The script is
in the plugin's install directory.

On Wednesday, September 12, 2012, David Kobia wrote:

> Noticed this about the Email Channel -- it has no setting. Maybe its the
> grouped options causing this issue?
> 
> https://a248.e.akamai.net/camo.github.com/f807447f23bc5f8e43245f3e43756af681ced05d/687474703a2f2f646c2e64726f70626f782e636f6d2f752f3530313635392f53637265656e73686f74732f697978736677705f6330636a2e706e67
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ushahidi/SwiftRiver/pull/267#issuecomment-8498470.

## 

Kind Regards,
Emmanuel Kala

Skype: emmanuel.kala

Judgement comes from experience, experience comes from poor judgement

**Comment by ekala** [comment]
@dkobia Ignore the comment above. Totally irrelevant. Yes, it must be the group options. Fixing...

**Comment by ekala** [comment]
Implemented in #284. Closing

**Pull request closed without merging**
