### PR TITLE
Added a river channel settings hook.

### PR DESCRIPTION
**Pull request by 69mb**
Added a new hook that allows plugins to add content to the river channel settings view a la:

### CODE REVIEW

**Comment by dkobia** [comment]
good to go -- also, how do we differentiate this from an Email channel?

Maybe call it a **River Dropbox**? Also, maybe add some kind of blurb that says **"SEND an email to your river dropbox and SwiftRiver will add it to the stream"**?

**Comment by ekala** [comment]
@dkobia The idea is to provide two alternatives:
- Email channel as an email address that is unique to the river
- Email channel as a plugin where you can configure a mailbox which the crawler can poll as per the schedule outlined in the **Configuring the crawler** section of README

**Comment by ekala** [comment]
@dkobia would like to close this out and merge into master. Is the explanation above ok? - ideally the plugin that implements this hook would be responsible for the display name of the channel.

Also, documentation for the plugin hook is up on the wiki: https://wiki.ushahidi.com/display/WIKI/Plugin+Hooks

**Comment by dkobia** [comment]
:+1: this is good to go. Explanation makes sense.

**Pull request merged**
