### PR TITLE
Messages: Implement Private Messaging

### LINKED ISSUE #203: Internal Messaging?
With more users coming on board, I'm realizing that it'd be really useful ping/message another user. I'm wondering if it'd be useful at all to allow people to send each other messages within the system? We can't see other users contact information and have no way of contacting them at the moment.

### PR DESCRIPTION
**Pull request by nlewis2142**
Github doesn't seem to handle merges into pull requests well. Please review -- should be ready for pull.

Closes #203

Users currently have no way to contact each other because the system does not share personal information. This will allow users to message each other through an easy to use link on their dashboard.

This most likely will have it's view redone at some point, but I tried to make it look decent. Suggestions on the view welcome.

CC: @69mb @ekala @dkobia

Routing: `<account>/messages(/<action>(/<id>))`

<a href="https://picasaweb.google.com/lh/photo/FcXRYBR9emhK4woT-NBVBXnM4QDb_ybfY9h6M6Fd0v4?feat=embedwebsite"></a><a href="https://picasaweb.google.com/lh/photo/RwNPx9BdiwMQi7S4KCM6FnnM4QDb_ybfY9h6M6Fd0v4?feat=embedwebsite"></a><a href="https://picasaweb.google.com/lh/photo/XKiuG4iwtk4hyWDWTjD3HHnM4QDb_ybfY9h6M6Fd0v4?feat=embedwebsite"></a><a href="https://picasaweb.google.com/lh/photo/evjFRo-khaeFvoAI9XqQ0XnM4QDb_ybfY9h6M6Fd0v4?feat=embedwebsite"></a><a href="https://picasaweb.google.com/lh/photo/OurXe7gcUYTtNCvhfXZTN3nM4QDb_ybfY9h6M6Fd0v4?feat=embedwebsite"></a>

<a href="https://picasaweb.google.com/lh/photo/iB0xEo2cRpdXBN6MmWUDmMjBVG_0f5B7oOHmZugTIg0?feat=embedwebsite"></a>

### CODE REVIEW

**Comment by 69mb** [comment]
The styling is inconsistent with the rest of Swift. Checkout the pattern portfolio at http://swiftriver.io/markup/patterns.php or on your local.

Specifically:
- The inbox and outbox should go to their own pages and use the page title pattern for this.
- Message listing could use the container pattern like we do for listing collaborators(http://bit.ly/QwESy1) but instead of just displaying name add the tile and the first few lines of the message.
- New messages should be created in a modal window.
- Messages should be displayed in a modal window too.
- Use the existing button styles.

Also use live search(similar to when adding a collaborator) when selecting a recipient instead of requiring the full nickname to be given.

Finally, make this a plugin.

**Comment by nlewis2142** [comment]
@69mb Yeah, I realized the styling was inconsistent. To be entirely honest I wasn't sure what it should look like, as the default markup really didn't match what I was looking for. I tried to re-use styling where appropriate but as you can see, the look came out quite differently. That said, good suggestions, I'll try to update the view a bit.

Working on
- Modal window for (new) messages
- Live search for selecting recipient
- Buttonizing the links on index
- Plugin-izing

A few questions though
- Inbox and outbox have their own pages. The page you see is a shortened version that shows the 5 most recent messages (or in the inbox's case, sorted by unread). If you click the view more links, the full inbox and outbox that show all messages -are- separated pages. Should I delete this quick view entirely? See `/messages/inbox`. If so, should inbox and outbox both have their own tabs on the nav?
- The container pattern does match the style of swiftriver, but it seems like it has a lot of whitespace.

**Comment by 69mb** [comment]
- I think keep the messaging tab on the dashboard with the summary but the inbox and outbox pages should not be sub content in the dashboard. They should take over the entire content area like we have for bucket/river settings.
- Thinking each message gets is container, + title, and preview it should come out ok.

**Comment by nlewis2142** [comment]
@69mb Not really sure how the container should look. I don't have much of an eye for design. What were you envisioning?

<a href="https://picasaweb.google.com/lh/photo/H_7NdC9Z1u94KzwLXXisLMjBVG_0f5B7oOHmZugTIg0?feat=embedwebsite"></a>

**Comment by 69mb** [comment]
+1

Only removed the messaging submodule from core. Think this should be an optional install per site.

**Pull request merged**
