### PR TITLE
River public token + changes for river rss feed.

### PR DESCRIPTION
**Pull request by 69mb**
- Changes to allow the feed writer plugin to present the feed icon and
  alternate links in the header.
- River now has a public access token.

### CODE REVIEW

**Comment by ekala** [comment]
Can't seem to find the RSS feed icon in the river view (the access token is all set)

River View

**Comment by 69mb** [comment]
Have you done a 'git submodule update' to pickup the updated feedwriter plugin?

**Comment by ekala** [comment]
Ah right. Got it now. Looks good for a merge

**Comment by nlewis2142** [comment]
(+1)

**Pull request merged**
